'use server';

import { mapBloodTypeToDB, mapUrgencyToDB } from '@/lib/utils/db-mapping';
import { createClient } from '@/lib/utils/supabase/server';
import { revalidatePath } from 'next/cache';

export async function submitContactForm(formData: {
  name: string;
  email: string;
  message: string;
  subject?: string;
}) {
    const supabase = await createClient();
    try {
    // Get current user if authenticated
    const { data: { user } } = await supabase.auth.getUser();
    
    // Check if user has submitted in the last 24 hours
    if (user) {
      const { data: recentMessages } = await supabase
        .from('contact_messages')
        .select('created_at')
        .eq('user_id', user.id)
        .gte('created_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString())
        .limit(1);
      
      if (recentMessages && recentMessages.length > 0) {
        return { 
          success: false, 
          message: 'আপনি ইতিমধ্যে আজ একটি বার্তা পাঠিয়েছেন। অনুগ্রহ করে ২৪ ঘণ্টা পরে আবার চেষ্টা করুন। (You can only send one message per day)' 
        };
      }
    }
    
    const { error } = await supabase
            .from('contact_messages')
            .insert([{
                name: formData.name,
                email: formData.email,
                message: formData.message,
                subject: formData.subject,
                user_id: user?.id || null
            }]);
        
        if (error) throw error;
        return { success: true, message: 'বার্তা সফলভাবে পাঠানো হয়েছে! (Message sent successfully!)' };
    } catch (error) {
        console.error('Contact Form Error:', error);
        return { success: false, message: 'বার্তা পাঠাতে ব্যর্থ হয়েছে। (Failed to send message.)' };
    }
}

export async function submitBloodRequest(formData: {
  patientName: string;
  bloodType: string;
  units: number;
  hospital: string;
  location: string;
  contactName: string;
  contactPhone: string;
  urgency: string;
  neededBy: string;
  reason?: string;
}) {
  const supabase = await createClient();
  try {
    // tracking_id is now generated by the database default value

    const { data, error } = await supabase
      .from('blood_requests')
      .insert([
        {
          patient_name: formData.patientName,
          blood_type: mapBloodTypeToDB(formData.bloodType),
          units: Number(formData.units),
          hospital: formData.hospital,
          location: formData.location,
          contact_name: formData.contactName,
          contact_phone: formData.contactPhone,
          urgency: mapUrgencyToDB(formData.urgency),
          needed_by: formData.neededBy,
          notes: formData.reason,
          status: 'PENDING',
          // tracking_id automatically generated
        }
      ])
      .select()
      .single();

    if (error) throw error;

    // Revalidate relevant paths
    revalidatePath('/donors'); 

    return { 
      success: true, 
      message: 'Blood request submitted successfully!',
      trackingId: data!.tracking_id // Use data returned from DB
    };

  } catch (error: any) {
    console.error('Submit Request Error:', error);
    return { success: false, message: error.message || 'Failed to submit request.' };
  }
}

export async function registerDonor(formData: any) {
    const supabase = await createClient();
    try {
        const { data: { user } } = await supabase.auth.getUser();
        
        if (!user) {
            return { success: false, message: 'You must be logged in to register as a donor.' };
        }

        const { error } = await supabase
            .from('profiles')
            .update({
                blood_type: mapBloodTypeToDB(formData.bloodGroup),
                location: formData.district + ', ' + formData.upazila, 
                last_donation: formData.lastDonation,
                age: new Date().getFullYear() - new Date(formData.dateOfBirth).getFullYear(),
                is_available: true,
            })
            .eq('id', user.id);

        if (error) throw error;
        return { success: true, message: 'Donor profile updated successfully!' };
    } catch (error: any) {
        console.error('Registration Error:', error);
        return { success: false, message: error.message || 'Failed to register.' };
    }
}
